<a href="https://colab.research.google.com/github/siddhartha237/MLT-Workshop/blob/main/(3)_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrices


## Import

In [ ]:
import numpy as np

## Matrix as a `NumPy` array

Everything in `NumPy` is an array. A matrix is also an array. Let us create a simple matrix:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

## Adding two matrices

Let us now add the following matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} + \textbf{B}  = \begin{bmatrix}
6 & 8\\
10 & 12
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
C = A + B
C

array([[ 6,  8],
       [10, 12]])

## Scaling a matrix

Scaling a matrix is nothing but element-wise multiplication:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

then,

$$
3 \textbf{M} = \begin{bmatrix}
3 & 6 & 9\\
12 & 15 & 18\\
21 & 24 & 27
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
3 * M

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

## Element-wise multiplication of matrices

Consider two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

The element-wise product is given by $\textbf{A} \odot \textbf{B}$:

$$
\textbf{C} = \textbf{A} \odot \textbf{B} = \begin{bmatrix}
5 & 12\\
21 & 32
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
C = A * B
C

array([[ 5, 12],
       [21, 32]])

## Element-wise functions of matrices

Given a matrix, we sometimes would want to apply a function to every element of the matrix. We will consider two examples.

### Example-1

For example, we may want to take the absolute value of all the elements. Let us say $f(x) = |x|$, then:

$$
\mathbf{A} = \begin{bmatrix}
-1 & 2\\
-3 & -4
\end{bmatrix}
$$

then:

$$
\begin{bmatrix}
f(-1) & f(2)\\
f(-3) & f(-4)
\end{bmatrix} =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
$$

In `NumPy`, this becomes:

In [ ]:
A = np.array([
    [-1, 2],
    [-3, -4]
])
np.abs(A)

array([[1, 2],
       [3, 4]])

### Example-2

We might want to square each element of the matrix. If $\textbf{A}$ is a matrix, then $\textbf{B}$ could be defined element-wise as follows:

$$
B_{ij} = A_{ij}^2
$$

Let us compute $\mathbf{B}$ for the following matrix:

$$
\mathbf{A} = \begin{bmatrix}
1 & \sqrt{2}\\
\sqrt{3} & 2
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.array([
    [1, np.sqrt(2)],
    [np.sqrt(3), 2]
])
A ** 2

array([[1., 2.],
       [3., 4.]])

## Transpose of a matrix

Given a matrix $\textbf{M}$:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

then, its transpose $\textbf{M}^{T}$ is:

$$
\textbf{M}^{T} = \begin{bmatrix}
1 & 4\\
2 & 5\\
3 & 6
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
np.transpose(M)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
M.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

Equivalently, we have:

In [ ]:
M.T

array([[1, 4],
       [2, 5],
       [3, 6]])

This is what we will be sticking to given that it is very close to the corresponding math notation.

## Shape and dimension of a matrix

Matrices are "two dimensional" arrays. So all matrices in `NumPy` have array-dimension equal to two. The shape of the `NumPy` array gives what we usually call the dimension of the matrix in the linear algebra sense.

Explore these two ideas for:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print('shape', M.shape)
print('numpy dimension', M.ndim)
print('size', M.size)

shape (2, 3)
numpy dimension 2
size 6


## Vectors as matrices

Each vector can be viewed as a matrix. Column vectors are matrices of shape $(d, 1)$. Row vectors are matrices of shape $(1, d)$. Let us look at how NumPy treats both these cases:


In [ ]:
x = np.array([1, 2, 3])
x = x[:, np.newaxis]
x

array([[1],
       [2],
       [3]])

In [ ]:
x = np.array([1, 2, 3])
x = x.reshape(3, 1)
x

array([[1],
       [2],
       [3]])

In [ ]:
x = np.array([1, 2, 3])
x = x[np.newaxis, :]
x

(1, 3)

In [ ]:
x = np.array([1, 2, 3])
x = x.reshape(1, 3)
x

array([[1, 2, 3]])

To create a row or column vector from a 1D NumPy array, we can use `np.newaxis`. Focus on the syntax for now; the reason we are doing this will become clear when we discuss indexing and slicing.

## Products involving matrices and vectors

We will look at the following products:
- matrix - matrix
- matrix - vector
- vector - matrix
- vector - vector

### Product of two matrices

Given two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
6 & 7\\
8 & 9\\
10 & 11
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} \times \textbf{B} = \begin{bmatrix}
52 & 58\\
124 & 139
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(6, 12).reshape(3, 2)
A @ B

array([[ 52,  58],
       [124, 139]])

### Product of a matrix and a (column) vector

Given the matrix $\mathbf{A}$ and the vector $\mathbf{x}$:

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}, \mathbf{x} = \begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
$$

The product $\mathbf{Ax}$ is given by:

$$
\mathbf{C} = \mathbf{A x} = \begin{bmatrix}
44\\
107\\
170
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.arange(1, 10).reshape(3, 3)
x = np.arange(6, 9)
A @ x

array([ 44, 107, 170])

### Product of a (row) vector and a matrix

Given the matrix $\mathbf{A}$ and the vector $\mathbf{x}$:

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}, \mathbf{x} = \begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
$$

The product $\mathbf{x}^T \mathbf{A}$ is given by:

$$
\mathbf{C} = \mathbf{x}^T \mathbf{A} = \begin{bmatrix}
90 & 111 & 132
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
x = np.arange(6, 9)
A = np.arange(1, 10).reshape(3, 3)
x @ A

array([ 90, 111, 132])

In [ ]:
# Note: for 1D arrays, transpose has no effect
x = np.arange(1, 4)
x.T

array([1, 2, 3])

### (Inner) Product of a (row) vector and a (column) vector

The product of a row vector and a column vector is nothing but the usual dot product:

$$
\mathbf{x}^T = \begin{bmatrix}
1 & 2 & 3
\end{bmatrix}, \quad
\mathbf{y} = \begin{bmatrix}
4\\
5\\
6
\end{bmatrix}
$$

The product $\mathbf{x}^T \mathbf{y}$ is then:

$$
\mathbf{x}^T \mathbf{y} = 32
$$

In `NumPy`:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x @ y

32

### (Outer) Product of a (column) vector and a (row) vector

The product of a column vector and a row vector is an outer product:

$$
\mathbf{x} = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}, \quad
\mathbf{y} = \begin{bmatrix}
4 & 5 & 6
\end{bmatrix}
$$

The product $\mathbf{x} \mathbf{y}^T$ is then:

$$
\mathbf{x} \mathbf{y}^T = \begin{bmatrix}
4 & 5 & 6\\
8 & 10 & 12\\
12 & 15 & 18
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
x = np.arange(1, 4)
y = np.arange(4, 7)
np.outer(x, y)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

Equivalently:

In [ ]:
x = np.arange(1, 4).reshape(3, 1) # column vector
y = np.arange(4, 7).reshape(1, 3) # row vector
x @ y # matrix-multiplication

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

## Matrix of zeros

In many algorithms, we might have to initialize a matrix with zeros. For example, consider a $2 \times 4$ matrix:

$$
\mathbf{M} = \begin{bmatrix}
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
zeros = np.zeros((2, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Matrix of ones

Similar to a matrix of zeros, we can come up with a matrix of ones.

$$
\mathbf{M} = \begin{bmatrix}
1 & 1\\
1 & 1\\
1 & 1
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
ones = np.ones((3, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Identity matrix

Often, we might have to deal with identity matrices. A $3 \times 3$ identity matrix is as follows:

$$
\mathbf{I} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Diagonal matrices

Another special kind of matrix. Let us create the following matrix:

$$
\mathbf{D} = \begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 2 & 0 & 0\\
0 & 0 & 3 & 0\\
0 & 0 & 0 & 4
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.diag([1, 2, 3, 4])

In [ ]:
M[1, 1]

2

In [ ]:
M[1][1]

2

## Indexing and Slicing

Just like lists in Python, `NumPy` arrays can be indexed and sliced. Slicing is useful if we want to work with a portion of an array. We will look at some examples.

### Example-1: Row-slice

We will extract the third row of the matrix $\mathbf{M}$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8\\
9 & 10
\end{bmatrix}
$$



In `NumPy`:

In [ ]:
M = np.arange(1, 11).reshape(5, 2)
M

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
M[2, :]

array([5, 6])

### Example-2: Column slice

Let us now extract the second column of the following matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.arange(1, 10).reshape(3, 3)
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
M[:, 1]

array([2, 5, 8])

### Example-3: Submatrix slice

Now, we want to extract the $2 \times 2$ submatrix colored in blue from $M$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & \color{blue}7 & \color{blue}8\\
9 & 10 & \color{blue}{11} & \color{blue}{12}\\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.arange(1, 17).reshape(4, 4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
M[1:3, 2:]

array([[ 7,  8],
       [11, 12]])

## Other Matrix Operations

There are several important matrix operations that we will list down here. The `np.linalg` module helps us perform these operations effortlessly.

### Rank

We can get the rank of a matrix as follows. For example:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8\\
9 & 10 & 11 & 12\\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In [ ]:
M = np.arange(1, 17).reshape(4, 4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.linalg.matrix_rank(M)

2

### Inverse

We can get the inverse as follows. For example:

$$
M = \begin{bmatrix}
3 & -4\\
4 & 3
\end{bmatrix}
$$

In [ ]:
M = np.array([
    [3, -4],
    [4, 3]
])
np.linalg.inv(M)

array([[ 0.12,  0.16],
       [-0.16,  0.12]])

In [ ]:
np.linalg.pinv(M) # pinv == inv for invertible (square) matrices

array([[ 0.12,  0.16],
       [-0.16,  0.12]])

In [ ]:
# Verify
M @ np.linalg.inv(M)

array([[ 1.00000000e+00,  0.00000000e+00],
       [-2.77555756e-17,  1.00000000e+00]])

### Pseuodoinverse

The pseudoinverse $\mathbf{M}^{\dagger}$ of any matrix $\mathbf{M}$ can be computed using NumPy.

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
3 & 6 & 9
\end{bmatrix}
$$


In [ ]:
M = np.array([
    [1, 2, 3],
    [3, 6, 9]
])
M_p = np.linalg.pinv(M) # normal equations linear regression

### Eigenvalues and Eigenvectors

Given a symmetric matrix $\mathbf{M}$ let us find its eigenvalues and eigenvectors:

$$
\mathbf{M} = \begin{bmatrix}
1 & 0 & -3\\
0 & 5 & 2\\
-3 & 2 & 8
\end{bmatrix}
$$

In [ ]:
M = np.array([
    [1, 0, -3],
    [0, 5, 2],
    [-3, 2, 8]
])
M

array([[ 1,  0, -3],
       [ 0,  5,  2],
       [-3,  2,  8]])

In [ ]:
np.array_equal(M, M.T)

True

In [ ]:
eigval, eigvec = np.linalg.eigh(M)

In [ ]:
eigval

array([-0.20942046,  4.36588492,  9.84353554])

In [ ]:
eigvec

array([[ 0.91805853,  0.26010485, -0.2991889 ],
       [-0.14209114,  0.92042494,  0.36418131],
       [ 0.37010626, -0.29182767,  0.88196257]])

In [ ]:
eigvec[:, 0]

array([ 0.91805853, -0.14209114,  0.37010626])

In [ ]:
M @ eigvec[:, 0], eigval[0] * eigvec[:, 0]

(array([-0.19226024,  0.02975679, -0.07750782]),
 array([-0.19226024,  0.02975679, -0.07750782]))

In [ ]:
np.allclose(M @ eigvec[:, 0], eigval[0] * eigvec[:, 0], 1e-5)

True